{% set name = "xarray-dataclasses" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xarray_dataclasses-{{ version }}.tar.gz
  sha256: e5e88e10622b2bcb4db6087d636327f6e0311ae66fa10e94ea571805ed6937ad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - poetry
  run:
    - numpy
    - python >=3.9
    - typing-extensions >=4.0,<5.0
    - xarray >=2022.3,<2024.0

test:
  imports:
    - xarray_dataclasses
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/astropenguin/xarray-dataclasses/
  summary: xarray data creation made easy by dataclass
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
