{% set name = "xarray-dataclasses" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xarray_dataclasses-{{ version }}.tar.gz
  sha256: abf80f444422dd987718e4c129ee7e9a302d342994b424d02c08d934a5ea4db6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - poetry
  run:
    - numpy
    - python >=3.9
    - typing-extensions >=4.0,<5.0
    - xarray >=2022.3,<2024.0

test:
  imports:
    - xarray_dataclasses
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/astropenguin/xarray-dataclasses/
  summary: xarray data creation made easy by dataclass
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
