{% set name = "xarray-dataclasses" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xarray_dataclasses-{{ version }}.tar.gz
  sha256: b82b454c5800bf9d488c188d6362428e6bc310d2fc35f96fa4063efa40d33267

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
  run:
    - numpy
    - python >={{ python_min }}
    - typing-extensions >=4.0,<5.0
    - xarray >=2022.3,<2024.0

test:
  imports:
    - xarray_dataclasses
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/astropenguin/xarray-dataclasses/
  summary: xarray data creation made easy by dataclass
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
